export const types = {
  ADD_IMAGE: 'ADD_IMAGE',
  GET_IMAGES: 'GET_IMAGES',
  GET_IMAGES_ERROR: 'GET_IMAGES_ERROR',
  GET_SELECTED_IMAGE: 'GET_SELECTED_IMAGE',
  HIDE_SELECTED_IMAGE: 'HIDE_SELECTED_IMAGE',
};
